[package]
name = "toml-mustache"
version = "0.1.0"
authors = ["goolord <zacharyachurchill@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mustache = "0.9.0"
toml = "0.5"
clap = "2.33.0"
